### PR TITLE
Fix `toJson` for cyclic values

### LINKED ISSUE #7326: Jsondata moduel `toJson` is hanging with the `CyclicValueReferenceError` error
### Description

with the 0.2.0 jasondata version we recieved the expected error [1] from the jsondata for the following sample[2], when doing `bal run`
[1] Expected error
```
error: {ballerina/lang.value}CyclicValueReferenceError {"message":"'json[]' value has cyclic reference"}
        at ballerina.data.jsondata.0:toJson(json_api.bal:58)
           hansaninissanka.jsondata.0:main(main.bal:10)
```
[2]Ballerina sample
```ballerina
import ballerina/io;
import ballerina/data.jsondata;

public function main() returns error? {
    io:println("Hello, World!");

    json[] x = [];
    x.push(x);
    json _  = check jsondata:toJson(x);
}
```
but with  the timestamp `0.3.0-20241028-143400-903c253`  of jsondata module , this particular example getting hang in `bal run` command 

### Steps to Reproduce

`bal run` the above [2] ballerina sample with the jsondata.module version `0.3.0-20241028-143400-903c253`

### Version

0.3.0-20241028-143400-903c253

### Environment Details (with versions)

_No response_

### PR DESCRIPTION
**Pull request by MaryamZi**
## Purpose

Fixes: https://github.com/ballerina-platform/ballerina-library/issues/7326

Also noticed https://github.com/ballerina-platform/ballerina-library/issues/7348

## Checklist
- [x] Linked to an issue
- [ ] Updated the changelog
- [x] Added tests
- [ ] Updated the spec
- [ ] Checked native-image compatibility

### CODE REVIEW

File: native/src/main/java/io/ballerina/lib/data/jsondata/json/Native.java [hunk 1]
```diff
@@ -82,6 +90,40 @@ public static Object parseStream(Environment env, BStream json, BMap<BString, Ob
...
+        return toJson(value, new HashSet<>());
+    }
+
+    public static Object toJson(Object value, Set<Object> visitedValues) {
+        if (!visitedValues.add(value)) {
+            throw DiagnosticLog.error(DiagnosticErrorCode.CYCLIC_REFERENCE);
+        }
+
+        if (value instanceof BArray listValue) {
+            int length = (int) listValue.getLength();
```
Comment (MaryamZi) [inline native/src/main/java/io/ballerina/lib/data/jsondata/json/Native.java:103]: Assumed this would be int for values created at runtime.

**Review by SasinduDilshara — APPROVED** [review]
