### PR TITLE
Fix toJson failing with repeated simple value members

### LINKED ISSUE #7362: Getting cyclic reference for a simple json with `datajson:toJson` method
### Description

> $Subject

This is happening after this fix: https://github.com/ballerina-platform/module-ballerina-data.jsondata/pull/51

### Steps to Reproduce

Try to run the following command in http after updating `stdlibDataJsonDataVersion=0.3.0-20241113-131800-94297e4` in the `gradle.properties` file.

```console
$ ./gradlew clean build -x :http-native:test -PbalTests=http2-tests

...

Running Tests with Coverage

        http2_tests
Couldn't complete the respond operation as the response has been already used.
error: the value has a cyclic reference
        at ballerina.data.jsondata.0:toJson(json_api.bal:58)
           ballerina.http.2.Request:setJsonPayload(http_request.bal:426)
           ballerina.http.2.Request:setPayload(http_request.bal:560)
           ballerina.http2_tests$test.2.$anonType$_190:$get$initial(tests/http2_client_upgrade_with_large_payload_test.bal:134)

        testClientUpgradewithLargePayload: has failed.

error: there are test failures
```

This is happening in this step: https://github.com/ballerina-platform/module-ballerina-http/blob/3feb04b51a86377cb78b0f8a9a8cc296ef4e5957/ballerina-tests/http2-tests/tests/http2_client_upgrade_with_large_payload_test.bal#L134 where we call `setPayload` with a raw json value. This function internally call the `jsondata:toJson` method

### Version

Ballerina SwanLake Update 11

### Environment Details (with versions)

Mac OS

### PR DESCRIPTION
**Pull request by MaryamZi**
## Purpose

Fixes: https://github.com/ballerina-platform/ballerina-library/issues/7362

## Checklist
- [x] Linked to an issue
- [ ] Updated the changelog
- [x] Added tests
- [ ] Updated the spec
- [ ] Checked native-image compatibility

### CODE REVIEW

File: native/src/main/java/io/ballerina/lib/data/jsondata/json/Native.java [hunk 1]
```diff
@@ -96,6 +97,14 @@ public static Object toJson(Object value) {
     }
 
     public static Object toJson(Object value, Set<Object> visitedValues) {
+        if (value == null) {
+            return null;
+        }
+
+        if (TypeUtils.getType(value).getTag() < 7) {
```
Comment (SasinduDilshara) [inline native/src/main/java/io/ballerina/lib/data/jsondata/json/Native.java]: Shall we add switch tag or a function like `getSimpleType` in here.
Otherwise this is not easy to understand

**Review by SasinduDilshara — APPROVED** [review]
